// <auto-generated />
using System;
using Empleate.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Empleate.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20181108192116_Empleate")]
    partial class Empleate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Empleate.Models.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellidos")
                        .IsRequired();

                    b.Property<int>("Celular");

                    b.Property<string>("Ciudad")
                        .IsRequired();

                    b.Property<string>("Correo")
                        .IsRequired();

                    b.Property<string>("Direccion")
                        .IsRequired();

                    b.Property<string>("EstadoCivil")
                        .IsRequired();

                    b.Property<DateTime>("FechaNacimiento");

                    b.Property<string>("Genero")
                        .IsRequired();

                    b.Property<string>("Imagen")
                        .IsRequired();

                    b.Property<string>("Nombre")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("Empleate.Models.Experiencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cargo")
                        .IsRequired();

                    b.Property<int>("EmpleadoId");

                    b.Property<DateTime>("Fin");

                    b.Property<DateTime>("Inicio");

                    b.Property<string>("Lugar")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("Experiencias");
                });

            modelBuilder.Entity("Empleate.Models.HabilidadEmpleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EmpleadoId");

                    b.Property<string>("Habilidad")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("HabilidadEmp");
                });

            modelBuilder.Entity("Empleate.Models.HabilidadRequerida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Habilidad")
                        .IsRequired();

                    b.Property<int>("OfertaId");

                    b.HasKey("Id");

                    b.ToTable("HabilidadesRequeridas");
                });

            modelBuilder.Entity("Empleate.Models.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EmpleadoId");

                    b.Property<string>("Idioma")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("Idiomas");
                });

            modelBuilder.Entity("Empleate.Models.LanguageRequerido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Idioma")
                        .IsRequired();

                    b.Property<int>("OfertaId");

                    b.HasKey("Id");

                    b.ToTable("IdiomasRequeridos");
                });

            modelBuilder.Entity("Empleate.Models.OfertaTrabajo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ciudad")
                        .IsRequired();

                    b.Property<string>("Descripcion")
                        .IsRequired();

                    b.Property<int>("EmpresaId");

                    b.Property<int>("ExperienciaMin");

                    b.Property<DateTime>("FechaLimite");

                    b.Property<DateTime>("HoraFin");

                    b.Property<DateTime>("HoraInicio");

                    b.Property<string>("Profesion")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Ofertas");
                });

            modelBuilder.Entity("Empleate.Models.Titulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .IsRequired();

                    b.Property<int>("EmpleadoId");

                    b.Property<string>("Grado")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("Titulos");
                });

            modelBuilder.Entity("Empleate.Models.Experiencia", b =>
                {
                    b.HasOne("Empleate.Models.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Empleate.Models.HabilidadEmpleado", b =>
                {
                    b.HasOne("Empleate.Models.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Empleate.Models.Language", b =>
                {
                    b.HasOne("Empleate.Models.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Empleate.Models.Titulo", b =>
                {
                    b.HasOne("Empleate.Models.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
